### ISSUE TITLE
problemi di installazione del war versione APIM 4.3.0

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [profesiait/weModI#2]
dopo aver generato il war con:
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: C:\Users\TD671\Documents\apache-maven-3.8.5
Java version: 11.0.23, vendor: Oracle Corporation, runtime: C:\Users\Compiler\Documents\jdk-11.0.23
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
copiato i files nelle cartelle di WSO2 (c:\wso2workspace\wso2am-4.3.0):

- ModISubscriptionAPI [api#am#modi.war] in /repository/deployment/server/webapps/
- ModISubscription [ModiSubscription-2.0.0.jar] in /repository/components/lib/
- ModIAuthenticator [ModiAuthenticator-2.0.0.jar] in /repository/components/lib/

in esecuzione ottengo i seguenti errori:

```
[2024-08-01 11:01:19,593] ERROR - [/api/am/modi] Error configuring application listener of class [org.springframework.web.context.ContextLoaderListener]
java.lang.ClassNotFoundException: org.springframework.web.context.ContextLoaderListener
        at org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader.loadClass(CarbonWebappClassLoader.java:195) ~[org.wso2.carbon.webapp.mgt_4.11.14.jar:?]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:488) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:470) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4389) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4914) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:303) ~[?:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:209) ~[?:?]
```

- `[2024-08-01 11:01:19,593] ERROR - [/api/am/modi] Skipped installing application listeners due to previous error(s)`
- `[2024-08-01 11:01:19,593] ERROR - StandardContext One or more listeners failed to start. Full details will be found in the appropriate container log file`
- `[2024-08-01 11:01:19,595] ERROR - StandardContext Context [/api/am/modi] startup failed due to previous errors`
- `[2024-08-01 11:01:19,676] ERROR - CarbonTomcat Cannot stop context`

```
org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_stop]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/api/am/modi]] in state [DESTROYED]

        at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:409) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:229) ~[tomcat_9.0.85.wso2v1.jar:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:321) ~[?:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:209) ~[?:?]
```
segue ll log completo [wso2carbon.zip](https://github.com/user-attachments/files/16454258/wso2carbon.zip)

**Comment by ggianoglio** [comment]
La versione 4.3 non è attualmente supportata.
